SOCIAL_AUTH_LINKEDIN_OAUTH2_KEY = '77yh66115w1j9n'           #Client ID:
SOCIAL_AUTH_LINKEDIN_OAUTH2_SECRET = 'bLkidGQFbacIUIGI'      #Client Secret:

SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/home/'
SOCIAL_AUTH_LOGIN_URL = '/'

